import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Language = 'ko' | 'en' | 'zh' | 'ja';

interface AppSettingsContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  darkMode: boolean;
  setDarkMode: (dark: boolean) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ko: {
    home: '홈',
    history: '기록',
    competitions: '대회',
    stats: '통계',
    settings: '설정',
    newRound: '새 라운딩',
    recentRounds: '최근 라운딩',
    totalRounds: '총 라운드',
    avgScore: '평균 타수',
    bestScore: '최고 기록',
    noRecords: '아직 기록이 없어요',
    startFirst: '첫 라운드를 시작해보세요!',
    score: '타',
    par: '파',
    birdiePlus: '버디+',
    putting: '퍼팅',
    share: '공유하기',
    delete: '삭제',
    deleteConfirm: '이 기록을 삭제할까요?',
    copied: '클립보드에 복사되었어요!',
    roundDetail: '라운드 상세',
    outCourse: 'OUT COURSE',
    inCourse: 'IN COURSE',
    birdie: '버디',
    bogey: '보기',
    doublePlus: '더블+',
    eagle: '이글',
    holeInOne: '홀인원',
    shotAnalysis: '샷 분석',
    personalBest: '개인 기록',
    myPerformance: '내 성적 요약',
    lastRounds: '번의 라운딩 기준',
    basedOn: '지난 ',
    hole: '홀',
    totalScore: '총점',
    finish: '끝내기',
    previous: '이전',
    next: '다음',
    complete: '완료',
    startRound: '라운딩 시작',
    courseName: '골프장 이름',
    coursePlaceholder: '예: 남부 컨트리클럽',
    friends: '친구',
    invite: '친구 초대하기',
    inviteDesc: '초대 코드를 보내서 친구와 연결하세요',
    myFriends: '내 친구',
    addFriend: '추가',
    noFriends: '아직 친구가 없어요',
    addFriendHint: '초대 코드를 공유하거나 친구를 추가하세요!',
    profile: '프로필',
    editName: '이름 변경',
    appearance: '외관',
    darkMode: '다크 모드',
    notifications: '알림',
    notificationsDesc: '친구의 라운딩 시작 알림',
    about: '앱 정보',
    version: '버전',
    competitionsInfo: '대회 안내',
    competitionsTitle: '대회 기능',
    competitionsDesc: '친구들과 함께 라운딩 대회를 할 수 있어요!',
    compStep1: '대회 만들기',
    compStep2: '친구 초대하기',
    compStep3: '각자 라운딩 후 결과 비교',
    compStep4: '순위 확인하고 결과 공유',
    activeCompetitions: '진행중인 대회',
    noCompetitions: '진행중인 대회가 없어요',
    createComp: '새 대회 만들기',
    compName: '대회 이름',
    compNamePlaceholder: '예: 3월 Monthly',
    cancel: '취소',
    create: '만들기',
    participants: '참가자',
    join: '참가하기',
    ranking: '현재 순위',
    status: '상태',
    pending: '대기중',
    active: '진행중',
    finished: '종료',
    competitionCreated: '대회 만들기',
    save: '저장',
    nameUpdated: '이름이 변경되었습니다',
    holeCount: '홀',
    loginWithGoogle: 'Google로 로그인',
    loggedIn: 'Google 로그인됨',
    logout: '로그아웃',
  },
  en: {
    home: 'Home',
    history: 'History',
    competitions: 'Competitions',
    stats: 'Stats',
    settings: 'Settings',
    newRound: 'New Round',
    recentRounds: 'Recent Rounds',
    totalRounds: 'Total Rounds',
    avgScore: 'Avg Score',
    bestScore: 'Best Score',
    noRecords: 'No records yet',
    startFirst: 'Start your first round!',
    score: 'score',
    par: 'Par',
    birdiePlus: 'Birdie+',
    putting: 'Putting',
    share: 'Share',
    delete: 'Delete',
    deleteConfirm: 'Delete this record?',
    copied: 'Copied to clipboard!',
    roundDetail: 'Round Detail',
    outCourse: 'OUT COURSE',
    inCourse: 'IN COURSE',
    birdie: 'Birdie',
    bogey: 'Bogey',
    doublePlus: 'Double+',
    eagle: 'Eagle',
    holeInOne: 'Hole in One',
    shotAnalysis: 'Shot Analysis',
    personalBest: 'Personal Best',
    myPerformance: 'My Performance',
    lastRounds: 'rounds',
    basedOn: 'Based on ',
    hole: 'Hole',
    totalScore: 'Total',
    finish: 'Finish',
    previous: 'Previous',
    next: 'Next',
    complete: 'Complete',
    startRound: 'Start Round',
    courseName: 'Course Name',
    coursePlaceholder: 'e.g. South Country Club',
    friends: 'Friends',
    invite: 'Invite Friends',
    inviteDesc: 'Share invite code to connect with friends',
    myFriends: 'My Friends',
    addFriend: 'Add',
    noFriends: 'No friends yet',
    addFriendHint: 'Share invite code or add friends!',
    profile: 'Profile',
    editName: 'Edit Name',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    notifications: 'Notifications',
    notificationsDesc: 'Notify when friends start round',
    about: 'About',
    version: 'Version',
    competitionsInfo: 'Competitions Info',
    competitionsTitle: 'Competition Feature',
    competitionsDesc: 'Compete with friends in golf rounds!',
    compStep1: 'Create Competition',
    compStep2: 'Invite Friends',
    compStep3: 'Play your rounds',
    compStep4: 'Check rankings & share results',
    activeCompetitions: 'Active Competitions',
    noCompetitions: 'No active competitions',
    createComp: 'Create Competition',
    compName: 'Competition Name',
    compNamePlaceholder: 'e.g. March Monthly',
    cancel: 'Cancel',
    create: 'Create',
    participants: 'Participants',
    join: 'Join',
    ranking: 'Ranking',
    status: 'Status',
    pending: 'Pending',
    active: 'Active',
    finished: 'Finished',
    competitionCreated: 'Create Competition',
    save: 'Save',
    nameUpdated: 'Name updated',
    holeCount: 'holes',
    loginWithGoogle: 'Login with Google',
    loggedIn: 'Logged in with Google',
    logout: 'Logout',
  },
  zh: {
    home: '首页',
    history: '记录',
    competitions: '比赛',
    stats: '统计',
    settings: '设置',
    newRound: '新回合',
    recentRounds: '最近回合',
    totalRounds: '总回合数',
    avgScore: '平均分',
    bestScore: '最佳成绩',
    noRecords: '暂无记录',
    startFirst: '开始您的第一个回合！',
    score: '分',
    par: '标准杆',
    birdiePlus: '小鸟+',
    putting: '推杆',
    share: '分享',
    delete: '删除',
    deleteConfirm: '删除此记录？',
    copied: '已复制到剪贴板！',
    roundDetail: '回合详情',
    outCourse: '前九洞',
    inCourse: '后九洞',
    birdie: '小鸟',
    bogey: '柏忌',
    doublePlus: '双柏忌+',
    eagle: '老鹰',
    holeInOne: '一杆进洞',
    shotAnalysis: '击球分析',
    personalBest: '个人最佳',
    myPerformance: '我的表现',
    lastRounds: '回合',
    basedOn: '基于 ',
    hole: '洞',
    totalScore: '总分',
    finish: '完成',
    previous: '上一个',
    next: '下一个',
    complete: '完成',
    startRound: '开始回合',
    courseName: '球场名称',
    coursePlaceholder: '例如：南方乡村俱乐部',
    friends: '朋友',
    invite: '邀请朋友',
    inviteDesc: '分享邀请码与朋友联系',
    myFriends: '我的朋友',
    addFriend: '添加',
    noFriends: '还没有朋友',
    addFriendHint: '分享邀请码或添加朋友！',
    profile: '个人资料',
    editName: '编辑姓名',
    appearance: '外观',
    darkMode: '深色模式',
    notifications: '通知',
    notificationsDesc: '朋友开始回合时通知',
    about: '关于',
    version: '版本',
    competitionsInfo: '比赛信息',
    competitionsTitle: '比赛功能',
    competitionsDesc: '与朋友一起参加高尔夫比赛！',
    compStep1: '创建比赛',
    compStep2: '邀请朋友',
    compStep3: '各自进行回合',
    compStep4: '查看排名并分享结果',
    activeCompetitions: '进行中的比赛',
    noCompetitions: '没有进行中的比赛',
    createComp: '创建比赛',
    compName: '比赛名称',
    compNamePlaceholder: '例如：三月月赛',
    cancel: '取消',
    create: '创建',
    participants: '参与者',
    join: '参加',
    ranking: '排名',
    status: '状态',
    pending: '待处理',
    active: '进行中',
    finished: '已结束',
    competitionCreated: '创建比赛',
    save: '保存',
    nameUpdated: '姓名已更新',
    holeCount: '洞',
    loginWithGoogle: '使用Google登录',
    loggedIn: '已登录Google',
    logout: '退出',
  },
  ja: {
    home: 'ホーム',
    history: '履歴',
    competitions: '大会',
    stats: '統計',
    settings: '設定',
    newRound: '新規ラウンド',
    recentRounds: '最近のラウンド',
    totalRounds: '総ラウンド数',
    avgScore: '平均スコア',
    bestScore: 'ベストスコア',
    noRecords: 'まだ記録がありません',
    startFirst: '最初のラウンドを始めましょう！',
    score: '点',
    par: 'パー',
    birdiePlus: 'バーディ+',
    putting: 'パット',
    share: '共有',
    delete: '削除',
    deleteConfirm: 'この記録を削除しますか？',
    copied: 'クリップボードにコピーしました！',
    roundDetail: 'ラウンド詳細',
    outCourse: 'アウトコース',
    inCourse: 'インコース',
    birdie: 'バーディ',
    bogey: 'ボギー',
    doublePlus: 'ダボ+',
    eagle: 'イーグル',
    holeInOne: 'ホールインワン',
    shotAnalysis: 'ショット分析',
    personalBest: '自己ベスト',
    myPerformance: '私の成績',
    lastRounds: 'ラウンド',
    basedOn: 'に基づく ',
    hole: 'ホール',
    totalScore: '合計',
    finish: '終了',
    previous: '前へ',
    next: '次へ',
    complete: '完了',
    startRound: 'ラウンド開始',
    courseName: 'コース名',
    coursePlaceholder: '例：サウス カントリー クラブ',
    friends: '友達',
    invite: '友達を招待',
    inviteDesc: '招待コードを共有して友達とつながる',
    myFriends: '私の友達',
    addFriend: '追加',
    noFriends: 'まだ友達がいません',
    addFriendHint: '招待コードを共有するか友達を追加！',
    profile: 'プロフィール',
    editName: '名前を変更',
    appearance: '外観',
    darkMode: 'ダークモード',
    notifications: '通知',
    notificationsDesc: 'ラウンド開始時に通知',
    about: 'アプリについて',
    version: 'バージョン',
    competitionsInfo: '大会情報',
    competitionsTitle: '大会機能',
    competitionsDesc: '友達とゴルフラウンド大会をしよう！',
    compStep1: '大会を作成',
    compStep2: '友達を招待',
    compStep3: '各自ラウンド',
    compStep4: '順位確認と結果共有',
    activeCompetitions: '進行中の大会',
    noCompetitions: '進行中の大会はありません',
    createComp: '大会を作成',
    compName: '大会名',
    compNamePlaceholder: '例：3月マンスリー',
    cancel: 'キャンセル',
    create: '作成',
    participants: '参加者',
    join: '参加',
    ranking: 'ランキング',
    status: '状態',
    pending: '保留中',
    active: '進行中',
    finished: '終了',
    competitionCreated: '大会を作成',
    save: '保存',
    nameUpdated: '名前が更新されました',
    holeCount: 'ホール',
    loginWithGoogle: 'Googleでログイン',
    loggedIn: 'Googleでログイン中',
    logout: 'ログアウト',
  },
};

const AppSettingsContext = createContext<AppSettingsContextType | null>(null);

export const AppSettingsProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'ko';
  });
  
  const [darkMode, setDarkModeState] = useState(() => {
    const saved = localStorage.getItem('darkMode');
    return saved === 'true';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem('darkMode', String(darkMode));
    if (darkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [darkMode]);

  const setLanguage = (lang: Language) => setLanguageState(lang);
  const setDarkMode = (dark: boolean) => setDarkModeState(dark);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <AppSettingsContext.Provider value={{ language, setLanguage, darkMode, setDarkMode, t }}>
      {children}
    </AppSettingsContext.Provider>
  );
};

export const useAppSettings = () => {
  const context = useContext(AppSettingsContext);
  if (!context) {
    throw new Error('useAppSettings must be used within AppSettingsProvider');
  }
  return context;
};
